//Map that's responsible for Translating language from English to Arabic

import 'app_strings.dart';

Map<String, String> arabicLanguage = {
  //app Strings
  AppStrings.userName: "إسم المستخدم",
  AppStrings.rememberMe: "تذكرني",
  AppStrings.signInSubHeader: "قم بتسجيل دخولك للاستماع بجمبع حدمات  evex",
  AppStrings.or: "أو تسجيل الدخول بواسطة",
  AppStrings.home: "الرئيسية",
  AppStrings.welcomeToEvex: "مرحبا بك في إيفكس",
  AppStrings.category: "الفئات",
  AppStrings.other: "اخرى",
  AppStrings.cartEmpty: "سلة التسوق فارغة",
  AppStrings.enterYourProblem: "أدخل مشكلتك",
  AppStrings.startShopping: "ابدأ التسوق",
  AppStrings.validCardNumber: "رقم البطاقة غير صالح",
  AppStrings.chooseColor: "الرجاء اختيار اللون",
  AppStrings.chooseSize: "يرجى اختيار مقاس",
  AppStrings.usedCoupon: "لقد تم بالفعل استخدام القسيمة من قبل",
  AppStrings.welcomeToOurApp: "مرحبًا بكم في تطبيقنا",
  AppStrings.noAddressFound: "لم يتم العثور على عنوان",
  AppStrings.noAddressFoundSubtitle:
      "يجب عليك إضافة عنوان أولاً قبل أن تتمكن من إتمام عملية الشراء.",
  AppStrings.takeYourStyleEverywhereWithUs: "استمتع بالأزياء كلها معنا",
  AppStrings.onBoardingDescription2:
      'يمكنك جمع وإدارة الكوبونات، وتحويلها بسهولة إلى أموال نقدية، والتمتع بتوفير كبير على مشترياتك. حقق أقصى استفادة من مكافآتك ببضع نقرات فقط!',
  AppStrings.onBoardingDescription1:
      ' اكتشف evex، وجهتك النهائية للأزياء والملابس عالية الجودة. استكشف مجموعتنا الواسعة من المنتجات الأنيقة والعصرية لتجد بالضبط ما تحتاجه للارتقاء بخزانة ملابسك.',
  AppStrings.onBoardingDescription3:
      "شارك كوبون مع صديق، وعندما يستخدمها، ستحصل على كوبون خاصة بك لاستخدامها. إنها طريقة رائعة لمكافأة نفسك بينما تساعد أصدقائك على الادخار أيضًا!",
  AppStrings.carryYourStyle:
      'احمل أسلوبك معك أينما ذهبت. احصل على إمكانية الوصول الفوري إلى الأزياء والصفقات والمزيد من خلال تطبيقنا.',
  AppStrings.iis: 'هي',
  AppStrings.paymentDone: 'تم الدفع بنجاح',
  AppStrings.paymentDoneSubtitle:
      'لقد تم إتمام عملية الشراء بنجاح. يمكنك عرض تفاصيل طلبك في حسابك.',
  AppStrings.couponApplied: 'تم تطبيق القسيمة',
  AppStrings.giftApplied: 'هدية مطبقة',
  AppStrings.deliveredSubtitle: 'طلبك حاليا خارج للتسليم',
  AppStrings.orderReceivedSubtitle:
      'تم تأكيد الطلب. نحن نجهز العناصر الخاصة بك',
  AppStrings.pendingSubtitle: 'الطلب معلق. في انتظار التأكيد',
  AppStrings.deliveredForShipment: 'تم التسليم للشحن',
  AppStrings.orderReceived: 'تم استقبال الطلب',
  AppStrings.retry: 'اعادة المحاولة',
  AppStrings.deliveredForShipmentSubtitle: 'طلبك جاهز للشحن',
  AppStrings.inValidCvv: 'CVV غير صالح',
  AppStrings.allrequiredField: 'يجب ادخال جميع الحقول',
  AppStrings.passwordMustBeEntered: 'يجب  ادخال كلمه السر',
  AppStrings.passwordMustBeAtEightCharacters:
      'يجب ان تكون كلمه السر اكثر من ثمانيه حروف',
  AppStrings.top: 'افضل ',
  AppStrings.noOrders: 'لا توجد طلبات',
  AppStrings.flashSale: 'عروض حصرية',
  AppStrings.noDataFound: 'لا توجد بيانات',
  AppStrings.storeFor: " متجر  ",
  AppStrings.noOrdersdelivered: "لم يتم تسليم أي طلبات",
  AppStrings.noOrderspending: "لا توجد طلبات معلقة",
  AppStrings.setDefaultBtn: "تعيين كافتراضي",
  AppStrings.noSelectedItem: "لا يوجد عنصر محدد",
  AppStrings.fashionProducts: "لمنتجات الموضة",
  AppStrings.earnAndRedeem: "كسب واسترداد",
  AppStrings.coupons: " كوبونات",
  AppStrings.walletFeature: "ميزة المحفظة",
  AppStrings.withOur: ' معنا ',
  AppStrings.aCoupons: 'الكوبون',
  AppStrings.share: 'شارك ',
  AppStrings.newCollection: 'جديدة مجموعة',
  AppStrings.haveAccount: "هل لديك حساب بالفعل ؟",
  AppStrings.andGet: " واحصل على ",
  AppStrings.name: 'الاسم',
  AppStrings.signIn: 'تسجيل الدخول',
  AppStrings.signUp: 'انشاء حساب',
  AppStrings.forgotPassword: 'نسيت كلمة المرور؟',
  AppStrings.email: 'البريد الالكتروني',
  AppStrings.phoneNumber: 'الهاتف',
  AppStrings.password: 'كلمة المرور',
  AppStrings.confirmPassword: 'تاكيد كلمة المرور',
  AppStrings.confirm: 'تاكيد',
  AppStrings.date: 'تاريخ الميلاد',
  AppStrings.continu: 'متابعة',
  AppStrings.continueWithGoogle: "متابعة مع Google",
  AppStrings.continueWithApple: "متابعة مع Apple",
  AppStrings.getStartNow: "ابدأ الآن",
  AppStrings.skip: "تخطي",
  AppStrings.processFailed: "فشل العملية",
  AppStrings.resendCode: "اعادة ارسال الرمز",
  AppStrings.newPassword: "كلمة المرور الجديدة",
  AppStrings.rewards: "المكافآت",
  AppStrings.registerMerchantData: "تسجيل بيانات التاجر",
  AppStrings.tellAboutYourself: "عرفنا عن نفسك أكثر",
  AppStrings.firstName: "الأسم الأول",
  AppStrings.lastName: "الأسم الأخير",
  AppStrings.middleName: "الأسم الأوسط",
  AppStrings.verfiryPhone: "التحقق من رقم الهاتف",
  AppStrings.whatServices: "ماهي الخدمة التي تقدمها ؟",
  AppStrings.choosetheservice: "حدد الخدمات ",
  AppStrings.pleaseEnterServices: "يرجي إدخال الخدمة المقدمة من طرفك",
  AppStrings.chooseSrvices: "حدد الخدمات ",
  AppStrings.enterDetailsadders: "يرجي إدخال عنوانك التفصيلي بشكل صحيح",
  AppStrings.locatedyourLocation: "حدد موقعك",
  AppStrings.useCurrentLocation: "إستخدم موقعي الحالي",
  AppStrings.otherInformation: "معلومات اخري",
  AppStrings.otherlink: "رابط اخر ",
  AppStrings.pagelink: "رابط الصفحة ",
  AppStrings.pleaseChooseService: "يرجي تحديد الخدمة المقدمة من طرفك",
  AppStrings.additionalInformation: "معلومات إضافية ",
  AppStrings.customer: "حساب عميل",
  AppStrings.servicesProvide: "مقدم خدمة",
  AppStrings.error: "خطاء",
  AppStrings.newBooking: "حجز جديد",
  AppStrings.getway: "البوابات الحاصه بيك ",
  AppStrings.chooseCity: "اختار المدينه",
  AppStrings.enterFolllowingInformation: "يرجي إدخال المعلومات الأتية ",
  AppStrings.enterPhoneNamber:
      "يرجي إدخال رقم هاتف صحيح سنرسل لك كود تفعيل في رسالة نصية",
  AppStrings.pleasEnterTheFollowingInformation:
      "يرجي إدخال البيانات الأتية لإتمام عملية التسجيل",
  AppStrings.thisCodeWillBeValidFor2Minutes:
      'سيكون هذا الرمز صالحًا لمدة دقيقتين. ',
  AppStrings.weSentCodeTo: "أدخل رمز التحقق الذي أرسلناه إلى رقم الهاتف",
  AppStrings.canLogin:
      "يمكنك تسجيل الدخول الان وتقديم الخدمات المميزة في التطبيق المميز",
  AppStrings.verifyYourIdentity: "التحقق من ملكيه الحساب",
  AppStrings.completeYourInfoDescription:
      "أكمل التفاصيل الخاصة بك لبدء استخدام التطبيق",
  AppStrings.sucessActivate:
      "تهانياً ,جاري مراجعة طلبك وسيتم التواصل معك في حالة قبول الطلب",
  AppStrings.registerAsaNewCustomer: "سجل كعميل جديد",
  AppStrings.registerAsaServiceProvider: "سجل كمقدم خدمة",
  AppStrings.doYouAlreadyHaveAnAccount: " هل لديك حساب بالفعل ؟",
  AppStrings.registeraNewAccount: "تسجيل حساب جديد",
  AppStrings.registerNewAccount:
      "قم بتسجيل حساب جديد للاستمتاع بجميع خدمات evex",
  AppStrings.completeYourInfo: "اكمل معلوماتك",
  AppStrings.createAnAccountOrLogInTo:
      "إنشاء حساب أو تسجيل الدخول لاستكشاف معلومات عنا",
  AppStrings.enterStrongPasswords:
      'أدخل كلمة مرور قوية تحتوي على 8 أحرف على الأقل تتكون من أحرف وأرقام.',
  AppStrings.accountRecovery: "استرداد الحساب",
  AppStrings.enterTheDigit: "أدخل\nالرمز المكون من 4 أرقام",
  AppStrings.pleaseEnterYourEmailSoWeCan:
      'الرجاء إدخال بريدك الإلكتروني حتى نتمكن من إرسال\n الرمز إليك .',
  AppStrings.settings: "الاعدادات",
  AppStrings.accountDetails: "تفاصيل الحساب",
  AppStrings.myAccount: "حسابي",
  AppStrings.defaultBtn: "الافتراضي",
  AppStrings.streetName: "اسم الشارع",
  AppStrings.city: "المدينة",
  AppStrings.houseNumber: "رقم المنزل",
  AppStrings.delete: "مسح",
  AppStrings.floor: "الطابق",
  AppStrings.all: "الكل",
  AppStrings.enterPassword: "أدخل كلمة المرور",
  AppStrings.congratulations: "تهانينا",
  AppStrings.enterCouponCode: "أدخل رمز قسيمتك",
  AppStrings.walletSubtitle: "تمت إضافتها إلى محفظتك بعد استرداد قسائمك.",
  AppStrings.addNewAddress: "اضافة عنوان جديد",
  AppStrings.governnorate: "المحافظة",
  AppStrings.changePassword: "تغيير كلمة المرور",
  AppStrings.currentPassword: "كلمة المرور الحالية",
  AppStrings.myActivity: "نشاطي",
  AppStrings.myGift: "الهدايا",
  AppStrings.myWallet: "محفظتي",
  AppStrings.myOrders: "طلباتي",
  AppStrings.search: "بحث",
  AppStrings.trackMyOrder: "تتبع طلبي",
  AppStrings.trackOrder: "تتبع الطلب",
  AppStrings.myAddress: "عناويني",
  AppStrings.myCard: "بطاقاتي",
  AppStrings.changeLanguage: "تغيير اللغة",
  AppStrings.about: "حول evex",
  AppStrings.privacyPolicy: "سياسة الخصوصية",
  AppStrings.contactUs: "تواصل بنا",
  AppStrings.deleteAccount: "حذف الحساب",
  AppStrings.logout: "تسجيل الخروج",
  AppStrings.save: "حفظ",
  AppStrings.sent: "مرسل",
  AppStrings.received: "مستلم",
  AppStrings.sendCoupon: "ارسال كوبون",
  AppStrings.sendGiftTo: "ارسال هدية",
  AppStrings.send: "ارسال",
  AppStrings.cancel: "الغاء",
  AppStrings.giftSent: "تم إرسال الهدية",
  AppStrings.successfully: "بنجاح",
  AppStrings.to: "الي",
  AppStrings.evexWallet: "محفظة ايفولا",
  AppStrings.ok: "حسنا",
  AppStrings.lastTransaction: "المعاملة الاخيرة",
  AppStrings.orderId: "رقم الطلب",
  AppStrings.seeAll: "اظهار الكل",
  AppStrings.products: "المنتجات",
  AppStrings.chargeWallet: "شحن المحفظة",
  AppStrings.selectOption: "حدد خيارك",
  AppStrings.selectCoupon: "حدد كوبون",
  AppStrings.selectYourCoupon: "حدد كوبون",
  AppStrings.addCoupon: "أضف كود خصم",
  AppStrings.apply: "تطبيق",
  AppStrings.no: "لا",
  AppStrings.logoutTitle: "هل أنت متاكد من أنك تريد تسجيل الخروج",
  AppStrings.back: "رجوع",
  AppStrings.code: "كود",
  AppStrings.pending: "معلق",
  AppStrings.delivered: "تم التوصيل",
  AppStrings.viewDetails: "عرض التفاصيل",
  AppStrings.numOfProduct: "عدد المنتجات",
  AppStrings.orderDate: "تاريخ الطلب",
  AppStrings.paymentMethod: "طريقة الدفع",
  AppStrings.orderPrice: "سعر الطلب",
  AppStrings.orderDetails: "تفاصيل الطلب",
  AppStrings.sendGiftToSubtitle: "هل أنت متأكد أنك تريد إرسال\nهذه الهدية إلى",
  AppStrings.sendGiftToSubtitle2:
      'لقد تلقيت كوبون هدية سيتم تفعيلها عندما يستخدم صديقك الهدية',
  AppStrings.favorite: "المفضلة",
  AppStrings.myProfile: "حسابي",
  AppStrings.color: " الألوان",
  AppStrings.priceRange: "نطاق السعر",
  AppStrings.notifications: " الاشعارات",
  AppStrings.size: "الحجم",
  AppStrings.addToCart: "اضف للسلة",
  AppStrings.buyNow: " شراء الان",
  AppStrings.cart: "السلة",
  AppStrings.checkout: "الدفع",
  AppStrings.addNewCard: "اضافة بطاقة جديدة",
  AppStrings.pay: "ادفع",
  AppStrings.reset: "اعادة تعيين",
  AppStrings.showResults: "اظهار النتائج",
  AppStrings.description: "الوصف",
  AppStrings.couponCode: "كود الكوبون",
  AppStrings.giftCode: "كود الهدية",
  AppStrings.fillTheCouponCode: "ادخل كود الكوبون",
  AppStrings.fillTheGiftCode: "ادخل كود الهدية",
  AppStrings.cardHolderName: "اسم صاحب البطاقة",
  AppStrings.cardNumber: "رقم البطاقة",
  AppStrings.expiryDate: "تاريخ الانتهاء",
  AppStrings.subtotal: "المجموع الفرعي",
  AppStrings.shipping: "الشحن",
  AppStrings.taxes: "الضرائب",
  AppStrings.gift: "الهدية",
  AppStrings.coupon2: "كوبون",
  AppStrings.language: "اللغة",
  AppStrings.selectYourProblem: "حدد مشكلتك",
  AppStrings.total: "المجموع",
  AppStrings.attachments: "المرفقات",
  AppStrings.dropHereToAttachOr: "اسحب هنا لأضافة المرفقات",
  AppStrings.filter: "فلتر",

  AppStrings.upload: "رفع",
  AppStrings.reportSent: "تم الإبلاغ",
  AppStrings.deleteTitle: "هل أنت متاكد من أنك تريد حذف حسابك؟",
  AppStrings.reportSentSubtitle:
      "شكرًا لك على تقريرك. لقد تلقيناه وسنتواصل معك قريبًا.",

  AppStrings.searchByUserName: "ابحث عن طريق اسم المستخدم",
  AppStrings.welcomeTo: "evex مرحبا بك في ",
  AppStrings.enjoy: "إستمتع بالخدمات التي تقدمها لك",
  AppStrings.swipeToDelete: "اسحب لحذف حسابك",
  AppStrings.keepUsingevex: "استمر في استخدام evex",
  AppStrings.useIt: "استخدمه الآن",
  AppStrings.later: "لاحقا",
  AppStrings.newGift: 'هدية جديدة',
  AppStrings.giftCoupon2: "لقد تلقيت هدية جديدة من صديقك. يمكنك الآن استخدامها",
  AppStrings.giftCoupon: "لقد تلقيت كوبون هدية من evex لتسجيلك معنا لأول مرة",
  AppStrings.searchForProduct: "ابحث عن منتج",
  AppStrings.viewAll: "عرض الكل",
  AppStrings.tryItOn: "قم بتجريبها مع evex",
  AppStrings.walletTopUp: "محفظة توب اب",
  AppStrings.rechargeWallet: "إعادة شحن محفظتك",
  AppStrings.applyCouponsandGifts: "استخدم الكوبونات والهدايا",
  AppStrings.trackYourOrder: "تتبع طلبك",
  AppStrings.addFunds:
      " أضف الأموال إلى محفظتك باستخدام قسائمك واستمتع بمدفوعات سلسة!",
  AppStrings.followYourOrder:
      " تابع رحلة طلبك بسهولة من لحظة تقديمه حتى وصوله إلى باب منزلك!",
  AppStrings.useCouponsandGifts:
      "استخدم قسائمك وهداياك عند الدفع للحصول على خصومات على منتجاتك!",
  AppStrings.collectCoupons:
      "اجمع القسائم لشحن محفظتك واستخدمها لإجراء مدفوعات سلسة داخل التطبيق!",
  AppStrings.tryItOnSubtitle:
      "استخدم الكاميرا لمشاهدة مظهر المنتج عليك في الوقت الفعلي. جرّبه قبل الشراء!",
  AppStrings.recommendedProducts: "منتجات موصى بها",
  AppStrings.textCopied: "تم نسخ النص",
  AppStrings.eGP: 'جنيه',
  AppStrings.deleteAll: "حذف الكل",
  AppStrings.pleaseEnterTheAmount: "الرجاء ادخال المبلغ",
  AppStrings.amount: "المبلغ",
  AppStrings.emailOrPhoneNumber: "البريد الالكتروني او رقم الهاتف",
  AppStrings.chooseWayForRest:
      "يرجي إختيار طريقة التواصل لإعادة تعيين كلمة المرور الخاصة بك ",
  AppStrings.enterEmailToSendCode:
      "أدخل بريدك الإلكتروني، وسوف نرسل التحقق رمز إلى البريد الإلكتروني وسوف يتم ارسال رمز التحقق الخاص بك",
  AppStrings.sendOtp: "ارسال رمز التحقق",
};
